use crate::domain::{
    Advisor, AdvisorEvent, Candlestick, DomainError, Location,
    analysis::{Evaluate, Formation, Pattern},
};

pub trait SignalRepository {}

/// Represent a trading signal generated by an analyzer.
/// # Fields
/// - id: Unique identifier for the signal.
/// - timestamp: The time when the signal was generated.
/// - reason: The reason or condition that triggered the signal.
#[derive(Debug, Clone)]
pub struct Signal {
    location: Location,
    reason: String,
}

impl Signal {
    pub fn new(location: Location, reason: String) -> Self {
        Self { location, reason }
    }

    pub fn location(&self) -> &Location {
        &self.location
    }

    pub fn reason(&self) -> &str {
        &self.reason
    }
}

pub struct SignalAdvisor {
    activate_on: Vec<Formation>,
    look_for: Vec<Pattern>,
    at: Vec<Box<dyn Evaluate>>,
}

impl SignalAdvisor {
    pub fn new(
        activate_on: Vec<Formation>,
        look_for: Vec<Pattern>,
        at: Vec<Box<dyn Evaluate>>,
    ) -> Self {
        Self {
            activate_on,
            look_for,
            at,
        }
    }

    pub fn activate_on(&self) -> &Vec<Formation> {
        &self.activate_on
    }

    pub fn looking_for(&self) -> &Vec<Pattern> {
        &self.look_for
    }

    pub fn at(&self) -> &Vec<Box<dyn Evaluate>> {
        &self.at
    }

    pub fn is_activated_on(&self, formation: &Formation) -> bool {
        self.activate_on.contains(formation)
    }
}

impl Default for SignalAdvisor {
    fn default() -> Self {
        Self {
            activate_on: vec![Formation::BullTrendForm],
            look_for: vec![Pattern::BullReversalBar],
            at: Vec::new(),
        }
    }
}

impl Advisor for SignalAdvisor {
    fn evaluates(&self, candles: &[Candlestick]) -> Result<Vec<AdvisorEvent>, DomainError> {
        let mut signals = Vec::new();
        for pattern in &self.look_for {
            if let Some(location) = pattern.evaluator().evaluates(candles) {
                let signal = Signal::new(
                    location,
                    format!("Signal generated for pattern: {:?}", pattern),
                );
                signals.push(AdvisorEvent::SignalGenerated(signal));
            }
        }
        Ok(signals)
    }
}
