use chrono::{DateTime, Utc};

use crate::domain::{
    Advisor, AdvisorEvent, Candlestick, DomainError, Location,
    analysis::{Evaluate, Pattern},
    supervisor::structure::Structure,
};

pub trait SignalRepository {}

/// Represent a trading signal generated by an analyzer.
/// # Fields
/// - id: Unique identifier for the signal.
/// - timestamp: The time when the signal was generated.
/// - reason: The reason or condition that triggered the signal.
#[derive(Debug, Clone)]
pub struct Signal {
    location: Location,
    reason: String,
}

impl Signal {
    pub fn new(location: Location, reason: String) -> Self {
        Self { location, reason }
    }

    pub fn location(&self) -> &Location {
        &self.location
    }

    pub fn reason(&self) -> &str {
        &self.reason
    }
}

pub struct SignalAdvisor {
    activated_on: Vec<Structure>,
    looking_for: Vec<Pattern>,
    at: Vec<Box<dyn Evaluate>>,
}

impl Default for SignalAdvisor {
    fn default() -> Self {
        Self {
            activated_on: Vec::new(),
            looking_for: Vec::new(),
            at: Vec::new(),
        }
    }
}

impl Advisor for SignalAdvisor {
    fn evaluates(&self, candles: &[Candlestick]) -> Result<Vec<AdvisorEvent>, DomainError> {
        let mut signals = Vec::new();
        for pattern in &self.looking_for {
            if let Some(location) = pattern.evaluator().evaluates(candles) {
                let signal = Signal::new(
                    location,
                    format!("Signal generated for pattern: {:?}", pattern),
                );
                signals.push(AdvisorEvent::SignalGenerated(signal));
            }
        }
        Ok(signals)
    }
}
