use chrono::{DateTime, Utc};

use crate::domain::supervisor::structure::Structure;

type SignalId = uuid::Uuid;

/// Represent a trading signal generated by an analyzer.
/// # Fields
/// - id: Unique identifier for the signal.
/// - timestamp: The time when the signal was generated.
/// - reason: The reason or condition that triggered the signal.
#[derive(Debug, Clone)]
pub struct Signal {
    timestamp: DateTime<Utc>,
    reason: String,
}

impl Signal {
    pub fn new(timestamp: DateTime<Utc>, reason: String) -> Self {
        Self { timestamp, reason }
    }
}

pub struct SignalAdvisor {
    activated_on: Vec<Structure>,
    looking_for: Vec<Pattern>,
    at: Vec<KeyEntryPoint>,
}
