use chrono::{DateTime, Utc};

type SignalId = uuid::Uuid;

/// Represent a trading signal generated by an analyzer.
/// # Fields
/// - id: Unique identifier for the signal.
/// - timestamp: The time when the signal was generated.
/// - reason: The reason or condition that triggered the signal.
#[derive(Debug, Clone)]
pub struct Signal {
    id: SignalId,
    timestamp: DateTime<Utc>,
    reason: String,
}

impl Signal {
    pub fn new(id: SignalId, timestamp: DateTime<Utc>, reason: String) -> Self {
        Self {
            id,
            timestamp,
            reason,
        }
    }
}
