use chrono::{DateTime, Utc};

type ContextId = uuid::Uuid;

/// Represent a trading context generated by an analyzer.
/// # Fields
/// - id: Unique identifier for the signal.
/// - timestamp: The time when the signal was generated.
/// - reason: The reason or condition that triggered the signal.
#[derive(Debug, Clone)]
pub struct Context {
    id: ContextId,
    timestamp: DateTime<Utc>,
    reason: String,
}

impl Context {
    pub fn new(id: ContextId, timestamp: DateTime<Utc>, reason: String) -> Self {
        Self {
            id,
            timestamp,
            reason,
        }
    }
}
