@startuml
package "Market Data Context" {

class Market {
  +MarketId: UUID
  +Symbol : Symbol
  +Timeframe : Timeframe
  +Candlesticks : List<Candlestick>
  +TickSize : Decimal
  --
  + addCandlestick(Candlestick)
}

note right of Market::addCandlestick
  validateMonotonicity
  validatePriceIsAlignedToTickSize
end note

class Symbol {
  +Ticker : String
  +Exchange : String
}

enum Timeframe {
  M1
  M5
  M15
  ...
}

class Candlestick {
  +Timestamp : Timestamp
  +Open : Price
  +High : Price
  +Low : Price
  +Close : Price
  +Volume : Integer
}

Market "1" --> "*" Candlestick
Market --> Symbol
Market --> Timeframe

}

package "Analysis Context" {

class AnalyzerService {
  +evaluate(Market) : Setup
}

class Setup {
  +SetupId : UUID
  +Symbol: Symbol
  +Timeframe: Timeframe
  +Timestamp : Timestamp
  +Patterns : List<Pattern>
  +KeyEntryPoints : List<EntryPoint>
  +Indicators : List<Indicator>
  +State : Enum {Created, Activated, Invalidated, Completed}
}

class Pattern {
  +Id: String
  +Candlesticks: List<Candlestick>
}

class EntryPoint {
  +Id: String
  +value: Decimal
}

class Indicator {
  +Id: String
  +Parameters : Map
}

Setup "1" o-- "*" Indicator
Setup "1" o-- "*" Pattern
Setup "1" o-- "*" EntryPoint
AnalyzerService ..> Market
AnalyzerService ..> Setup

}
@enduml
