@startuml

box "Interface"
actor Provider
end box
box "Application"
participant AdvisorService
end box
box "Domain"
participant Market
participant Window
participant ContextAdvisor
collections SignalAdvisors
end box
box "Infrastructure"
database ContextRepository
database SignalRepository
end box

Provider -> AdvisorService: provide new candle
group New Candle
AdvisorService -> Market: AddCandle
Market -> Market: Validate Candle
Market -> Window: update
Market -> AdvisorService: event CandleAdded(Candlestick)
end
group Context Evaluation
AdvisorService -> ContextAdvisor: evaluate(market.window)
ContextAdvisor -> AdvisorService: List<event StructureDetected(Context)>
end
AdvisorService -> ContextRepository: save new Context
group Signal Evaluation
AdvisorService -> SignalAdvisors: evaluate(Market.window, Context)
SignalAdvisors -> AdvisorService: SignalGenerated(Signal)
end
AdvisorService -> SignalRepository: save new Signal

@enduml
